[workspace]
members = [ "basicTypes_Numbers/char-bol-unit", "basicTypes_Numbers/numbers",
	"first_1",
	"first_2", 
	"first_3", 
	"first_4", 
	"first_5", 
	"first_6", 
	"first_7", 
	"first_8", 
	"first_9",

] 
